import { Department } from "../types/department.types";

export const INITIAL_DEPARTMENTS: Department[] = [
  {
    id: "DEPT001",
    name: "Engineering",
    code: "ENG",
    head: "Suresh Iyer",
    status: "Active",
    employees: 820,
    activeEmployees: 805,
    onLeaveEmployees: 15,
    growth: 18,
    description: "Core technology development and infrastructure scaling.",
    createdDate: "Jan 15, 2023",
    lastUpdated: "Apr 20, 2026",
    parentDepartment: "None",
    teams: [
      { name: "Database Team", lead: "Arun Kumar" },
      { name: "Backend Team", lead: "Priya Nair" },
    ],
    budgetAmount: "₹1.2Cr",
    budgetUsedPct: 72,
    budgetUsedAmount: "₹86.4L",
    budgetStatus: "green",
  },
  {
    id: "DEPT002",
    name: "Sales",
    code: "SLS",
    head: "Vikram Singh",
    status: "Active",
    employees: 540,
    activeEmployees: 532,
    onLeaveEmployees: 8,
    growth: 12,
    description: "Revenue acquisition and client relationship onboarding.",
    createdDate: "Mar 10, 2023",
    lastUpdated: "Apr 18, 2026",
    parentDepartment: "None",
    teams: [
      { name: "Inbound Sales", lead: "John Doe" },
      { name: "Outbound Sales", lead: "Jane Smith" },
    ],
    budgetAmount: "₹85L",
    budgetUsedPct: 81,
    budgetUsedAmount: "₹68.8L",
    budgetStatus: "amber",
  },
  {
    id: "DEPT003",
    name: "Marketing",
    code: "MKT",
    head: "Sneha Patel",
    status: "Active",
    employees: 310,
    activeEmployees: 300,
    onLeaveEmployees: 10,
    growth: 8,
    description: "Product placement, digital campaigns, and branding initiatives.",
    createdDate: "Feb 20, 2023",
    lastUpdated: "Mar 15, 2026",
    parentDepartment: "None",
    teams: [
      { name: "SEO & Content", lead: "Alice Wonderland" },
      { name: "Performance Marketing", lead: "Bob Builder" },
    ],
    budgetAmount: "₹60L",
    budgetUsedPct: 65,
    budgetUsedAmount: "₹39L",
    budgetStatus: "green",
  },
  {
    id: "DEPT004",
    name: "HR",
    code: "HR",
    head: "Meera Thomas",
    status: "Active",
    employees: 180,
    activeEmployees: 176,
    onLeaveEmployees: 4,
    growth: 5,
    description: "Talent scouting, organizational benefits, and policy rollout.",
    createdDate: "Jan 05, 2023",
    lastUpdated: "Feb 28, 2026",
    parentDepartment: "None",
    teams: [
      { name: "Talent Acquisition", lead: "Sarah Connor" },
      { name: "Employee Relations", lead: "John Wick" },
    ],
    budgetAmount: "₹40L",
    budgetUsedPct: 58,
    budgetUsedAmount: "₹23.2L",
    budgetStatus: "green",
  },
  {
    id: "DEPT005",
    name: "Finance",
    code: "FIN",
    head: "Ananya Das",
    status: "Active",
    employees: 240,
    activeEmployees: 238,
    onLeaveEmployees: 2,
    growth: 6,
    description: "Corporate audits, payroll compliance, and bookkeeping operations.",
    createdDate: "Jun 01, 2023",
    lastUpdated: "Apr 10, 2026",
    parentDepartment: "None",
    teams: [
      { name: "Payroll & Benefits", lead: "Bruce Wayne" },
    ],
    budgetAmount: "₹55L",
    budgetUsedPct: 91,
    budgetUsedAmount: "₹50.05L",
    budgetStatus: "red",
    nearLimit: true,
  },
  {
    id: "DEPT006",
    name: "Operations",
    code: "OPS",
    head: "Priya Nair",
    status: "Inactive",
    employees: 757,
    activeEmployees: 740,
    onLeaveEmployees: 17,
    growth: 14,
    description: "Logistics fulfillment, quality checks, and supply parameters.",
    createdDate: "May 12, 2023",
    lastUpdated: "Dec 15, 2025",
    parentDepartment: "None",
    teams: [
      { name: "Logistics Team", lead: "Sanjay Gupta" },
    ],
    budgetAmount: "₹95L",
    budgetUsedPct: 78,
    budgetUsedAmount: "₹74.1L",
    budgetStatus: "amber",
  },
];
