import type { NewHire, EmployeeOption } from "../types/onboarding.types";

/* ─── New Hires (Onboarding List) ─── */
export const NEW_HIRES: NewHire[] = [
  {
    id: "nh1",
    initials: "PS",
    avatarColor: "#00B87C",
    name: "Priya Sharma",
    role: "Frontend Developer",
    dept: "Engineering",
    deptColor: "#00B87C",
    joiningDate: "2026-04-08",
    progress: 45,
    progressColor: "#00B87C",
    status: "on-track",
    daysInOnboarding: 3,
    expectedCompletion: "Apr 22, 2026",
    manager: "Suresh Iyer",
  },
  {
    id: "nh2",
    initials: "DK",
    avatarColor: "#14B8A6",
    name: "Dev Kumar",
    role: "Backend Developer",
    dept: "Engineering",
    deptColor: "#00B87C",
    joiningDate: "2026-04-08",
    progress: 20,
    progressColor: "#00B87C",
    status: "on-track",
    daysInOnboarding: 3,
    expectedCompletion: "Apr 22, 2026",
    manager: "Suresh Iyer",
  },
  {
    id: "nh3",
    initials: "AK",
    avatarColor: "#8B5CF6",
    name: "Aisha Khan",
    role: "UX Designer",
    dept: "Design",
    deptColor: "#8B5CF6",
    joiningDate: "2026-04-01",
    progress: 78,
    progressColor: "#00B87C",
    status: "on-track",
    daysInOnboarding: 7,
    expectedCompletion: "Apr 15, 2026",
    manager: "Neha Joshi",
  },
  {
    id: "nh4",
    initials: "LM",
    avatarColor: "#F59E0B",
    name: "Leo Martinez",
    role: "Sales Manager",
    dept: "Sales",
    deptColor: "#F59E0B",
    joiningDate: "2026-03-28",
    progress: 60,
    progressColor: "#F59E0B",
    status: "delayed",
    daysInOnboarding: 11,
    expectedCompletion: "Apr 11, 2026",
    manager: "Vikram Mehta",
  },
  {
    id: "nh5",
    initials: "RC",
    avatarColor: "#EF4444",
    name: "Riya Chandra",
    role: "Finance Analyst",
    dept: "Finance",
    deptColor: "#0EA5E9",
    joiningDate: "2026-03-25",
    progress: 90,
    progressColor: "#00B87C",
    status: "on-track",
    daysInOnboarding: 14,
    expectedCompletion: "Apr 8, 2026",
    manager: "Deepa Iyer",
  },
  {
    id: "nh6",
    initials: "SM",
    avatarColor: "#00B87C",
    name: "Sanjay Mehta",
    role: "DevOps Engineer",
    dept: "Engineering",
    deptColor: "#00B87C",
    joiningDate: "2026-03-20",
    progress: 100,
    progressColor: "#00B87C",
    status: "complete",
    daysInOnboarding: 19,
    expectedCompletion: "Apr 3, 2026",
    manager: "Arun Nair",
  },
  {
    id: "nh7",
    initials: "TK",
    avatarColor: "#0EA5E9",
    name: "Tanya Kapoor",
    role: "Marketing Lead",
    dept: "Marketing",
    deptColor: "#EC4899",
    joiningDate: "2026-03-15",
    progress: 35,
    progressColor: "#EF4444",
    status: "at-risk",
    daysInOnboarding: 24,
    expectedCompletion: "Mar 29, 2026",
    manager: "Sneha Reddy",
  },
  {
    id: "nh8",
    initials: "PD",
    avatarColor: "#14B8A6",
    name: "Pranav Das",
    role: "Data Analyst",
    dept: "Analytics",
    deptColor: "#14B8A6",
    joiningDate: "2026-04-15",
    progress: 0,
    progressColor: "#94A3B8",
    status: "pre-joining",
    daysInOnboarding: 0,
    expectedCompletion: "Apr 29, 2026",
    manager: "Rajesh Kumar",
  },
];

/* ─── Employee dropdown options (for Initiate modal) ─── */
export const EMPLOYEE_OPTIONS: EmployeeOption[] = [
  { id: "e1", name: "Priya Sharma", role: "Frontend Developer", dept: "Engineering" },
  { id: "e2", name: "Dev Kumar", role: "Backend Developer", dept: "Engineering" },
  { id: "e3", name: "Aisha Khan", role: "UX Designer", dept: "Design" },
  { id: "e4", name: "Leo Martinez", role: "Sales Manager", dept: "Sales" },
  { id: "e5", name: "Riya Chandra", role: "Finance Analyst", dept: "Finance" },
  { id: "e6", name: "Sanjay Mehta", role: "DevOps Engineer", dept: "Engineering" },
  { id: "e7", name: "Tanya Kapoor", role: "Marketing Lead", dept: "Marketing" },
  { id: "e8", name: "Pranav Das", role: "Data Analyst", dept: "Analytics" },
  { id: "e9", name: "Suresh Iyer", role: "Engineering Manager", dept: "Engineering" },
  { id: "e10", name: "Neha Joshi", role: "Design Lead", dept: "Design" },
];
