/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import {
  Organization,
  PlatformUser,
  Subscription,
  FeatureFlag,
  RoleTemplate,
  Integration,
  ApiKey,
  WebhookEndpoint,
  AuditLogEntry,
  SupportTicket,
  TicketMessage,
  Announcement,
  EmailTemplate,
  NotificationRule,
  BackupSnapshot,
  BackupSchedule,
  BrandingConfig,
  SecurityPolicy,
  SecurityEvent,
  AiFeatureToggle,
  AiUsageStat,
  PlatformSettings,
  AdminTeamMember,
} from "./types";

// Helper to load or initialize from localStorage
function getStore<T>(key: string, defaultVal: T): T {
  try {
    const item = localStorage.getItem(`ems_${key}`);
    return item ? JSON.parse(item) : defaultVal;
  } catch (e) {
    console.warn(`Error reading localStorage key ${key}`, e);
    return defaultVal;
  }
}

function saveStore<T>(key: string, val: T) {
  try {
    localStorage.setItem(`ems_${key}`, JSON.stringify(val));
  } catch (e) {
    console.error(`Error writing localStorage key ${key}`, e);
  }
}

// ==========================================
// INITIAL SEED DATA
// ==========================================

const initialOrganizations: Organization[] = [
  {
    id: "org-1",
    name: "Acme Enterprise",
    domain: "acme.com",
    logoUrl: "",
    status: "Active",
    plan: "Enterprise",
    userCount: 450,
    seatLimit: 500,
    mrr: 4500,
    industry: "Technology",
    region: "North America",
    ownerEmail: "admin@acme.com",
    joinedAt: "2024-01-15T08:00:00Z",
    lastActiveAt: "2026-06-20T01:00:00Z",
  },
  {
    id: "org-2",
    name: "Apex Global",
    domain: "apex-corp.com",
    logoUrl: "",
    status: "Active",
    plan: "Growth",
    userCount: 120,
    seatLimit: 150,
    mrr: 1200,
    industry: "Financial Services",
    region: "Europe",
    ownerEmail: "billing@apex-corp.com",
    joinedAt: "2024-05-10T12:30:00Z",
    lastActiveAt: "2026-06-19T23:45:00Z",
  },
  {
    id: "org-3",
    name: "Stellar Tech SRL",
    domain: "stellar.io",
    logoUrl: "",
    status: "Trial",
    plan: "Starter",
    userCount: 8,
    seatLimit: 15,
    mrr: 0,
    industry: "SpaceTech",
    region: "Europe",
    ownerEmail: "contact@stellar.io",
    joinedAt: "2026-06-10T09:15:00Z",
    lastActiveAt: "2026-06-20T01:10:00Z",
    trialEndsAt: "2026-07-10T09:15:00Z",
  },
  {
    id: "org-4",
    name: "Nova Media Ltd",
    domain: "novamedia.co.uk",
    logoUrl: "",
    status: "Suspended",
    plan: "Growth",
    userCount: 85,
    seatLimit: 100,
    mrr: 850,
    industry: "Media & Entertainment",
    region: "United Kingdom",
    ownerEmail: "compliance@novamedia.co.uk",
    joinedAt: "2025-02-01T14:00:00Z",
    lastActiveAt: "2026-06-12T10:30:00Z",
  },
  {
    id: "org-5",
    name: "Zenith Agri",
    domain: "zenithagri.co",
    logoUrl: "",
    status: "Inactive",
    plan: "Starter",
    userCount: 3,
    seatLimit: 10,
    mrr: 99,
    industry: "Agriculture",
    region: "Latin America",
    ownerEmail: "lucas@zenithagri.co",
    joinedAt: "2025-08-20T16:00:00Z",
    lastActiveAt: "2026-05-30T15:20:00Z",
  },
  {
    id: "org-6",
    name: "Epsilon Logistics",
    domain: "epsilon.com",
    logoUrl: "",
    status: "Active",
    plan: "Enterprise",
    userCount: 890,
    seatLimit: 1000,
    mrr: 8900,
    industry: "Logistics",
    region: "Asia Pacific",
    ownerEmail: "ops@epsilon.com",
    joinedAt: "2024-11-12T04:20:00Z",
    lastActiveAt: "2026-06-20T00:55:00Z",
  },
  {
    id: "org-7",
    name: "Cyberdyne Systems",
    domain: "cyberdyne.io",
    logoUrl: "",
    status: "Active",
    plan: "Enterprise",
    userCount: 210,
    seatLimit: 300,
    mrr: 4500,
    industry: "AI & Robotics",
    region: "North America",
    ownerEmail: "miles.dyson@cyberdyne.io",
    joinedAt: "2025-09-01T10:00:00Z",
    lastActiveAt: "2026-06-20T01:12:00Z",
  },
  {
    id: "org-8",
    name: "Initech",
    domain: "initech.com",
    logoUrl: "",
    status: "Pending",
    plan: "Starter",
    userCount: 1,
    seatLimit: 10,
    mrr: 0,
    industry: "Software",
    region: "North America",
    ownerEmail: "peter.gibbons@initech.com",
    joinedAt: "2026-06-18T18:30:00Z",
    lastActiveAt: "2026-06-18T18:35:00Z",
  },
  {
    id: "org-9",
    name: "Wayne Enterprises",
    domain: "waynecorp.com",
    logoUrl: "",
    status: "Active",
    plan: "Enterprise",
    userCount: 4500,
    seatLimit: 5000,
    mrr: 45000,
    industry: "Defense & Heavy Industry",
    region: "North America",
    ownerEmail: "bruce@waynecorp.com",
    joinedAt: "2023-10-01T09:00:00Z",
    lastActiveAt: "2026-06-20T01:05:00Z",
  },
  {
    id: "org-10",
    name: "Umbrella Biotech",
    domain: "umbrellacorp.com",
    logoUrl: "",
    status: "Suspended",
    plan: "Enterprise",
    userCount: 45,
    seatLimit: 250,
    mrr: 3500,
    industry: "Biotechnology",
    region: "Europe",
    ownerEmail: "albert.wesker@umbrellacorp.com",
    joinedAt: "2025-03-15T07:11:00Z",
    lastActiveAt: "2026-06-05T20:44:00Z",
  },
];

const initialUsers: PlatformUser[] = [
  {
    id: "user-1",
    name: "Alice Vance",
    email: "admin@acme.com",
    status: "Active",
    role: "Org Admin",
    organization: "Acme Enterprise",
    organizationId: "org-1",
    lastLoginAt: "2026-06-20T01:00:00Z",
    mfaEnabled: true,
    joinedAt: "2024-01-15T08:00:00Z",
  },
  {
    id: "user-2",
    name: "Bob Carter",
    email: "bob@acme.com",
    status: "Active",
    role: "HR Manager",
    organization: "Acme Enterprise",
    organizationId: "org-1",
    lastLoginAt: "2026-06-19T17:30:00Z",
    mfaEnabled: false,
    joinedAt: "2024-03-10T11:00:00Z",
  },
  {
    id: "user-3",
    name: "Charlie Dunn",
    email: "charlie@acme.com",
    status: "Active",
    role: "Employee",
    organization: "Acme Enterprise",
    organizationId: "org-1",
    lastLoginAt: "2026-06-18T09:00:00Z",
    mfaEnabled: false,
    joinedAt: "2024-05-12T14:22:00Z",
  },
  {
    id: "user-4",
    name: "Sarah Connor",
    email: "sarah@cyberdyne.io",
    status: "Active",
    role: "Org Admin",
    organization: "Cyberdyne Systems",
    organizationId: "org-7",
    lastLoginAt: "2026-06-20T01:12:00Z",
    mfaEnabled: true,
    joinedAt: "2025-09-01T10:15:00Z",
  },
  {
    id: "user-5",
    name: "Peter Gibbons",
    email: "peter.gibbons@initech.com",
    status: "Pending",
    role: "Org Admin",
    organization: "Initech",
    organizationId: "org-8",
    lastLoginAt: "2026-06-18T18:35:00Z",
    mfaEnabled: false,
    joinedAt: "2026-06-18T18:30:00Z",
  },
  {
    id: "user-6",
    name: "Bruce Wayne",
    email: "bruce@waynecorp.com",
    status: "Active",
    role: "Org Admin",
    organization: "Wayne Enterprises",
    organizationId: "org-9",
    lastLoginAt: "2026-06-20T01:05:00Z",
    mfaEnabled: true,
    joinedAt: "2023-10-01T09:00:00Z",
  },
  {
    id: "user-7",
    name: "Lucius Fox",
    email: "lucius@waynecorp.com",
    status: "Active",
    role: "HR Manager",
    organization: "Wayne Enterprises",
    organizationId: "org-9",
    lastLoginAt: "2026-06-20T00:30:00Z",
    mfaEnabled: true,
    joinedAt: "2023-10-05T10:00:00Z",
  },
  {
    id: "user-8",
    name: "Albert Wesker",
    email: "albert.wesker@umbrellacorp.com",
    status: "Suspended",
    role: "Org Admin",
    organization: "Umbrella Biotech",
    organizationId: "org-10",
    lastLoginAt: "2026-06-05T20:44:00Z",
    mfaEnabled: true,
    joinedAt: "2025-03-15T07:11:00Z",
  },
  {
    id: "user-9",
    name: "Thomas Anderson",
    email: "neo@metacortex.net",
    status: "Inactive",
    role: "Employee",
    organization: "Acme Enterprise",
    organizationId: "org-1",
    lastLoginAt: "2026-04-10T12:00:00Z",
    mfaEnabled: false,
    joinedAt: "2025-01-10T08:00:00Z",
  },
  {
    id: "user-10",
    name: "Tony Stark",
    email: "tony@stark.com",
    status: "Active",
    role: "Org Admin",
    organization: "Acme Enterprise",
    organizationId: "org-1",
    lastLoginAt: "2026-06-20T01:15:00Z",
    mfaEnabled: true,
    joinedAt: "2024-02-20T10:00:00Z",
  },
];

const initialSubscriptions: Subscription[] = [
  {
    id: "sub-1",
    organization: "Acme Enterprise",
    organizationId: "org-1",
    plan: "Enterprise",
    status: "Active",
    billingCycle: "Annual",
    amount: 54000,
    currency: "USD",
    startDate: "2024-01-15",
    renewalDate: "2027-01-15",
    paymentMethodLast4: "4242",
    failedPaymentCount: 0,
  },
  {
    id: "sub-2",
    organization: "Apex Global",
    organizationId: "org-2",
    plan: "Growth",
    status: "Active",
    billingCycle: "Monthly",
    amount: 1200,
    currency: "EUR",
    startDate: "2024-05-10",
    renewalDate: "2026-07-10",
    paymentMethodLast4: "9876",
    failedPaymentCount: 0,
  },
  {
    id: "sub-3",
    organization: "Stellar Tech SRL",
    organizationId: "org-3",
    plan: "Starter",
    status: "Trial",
    billingCycle: "Monthly",
    amount: 0,
    currency: "USD",
    startDate: "2026-06-10",
    renewalDate: "2026-07-10",
    paymentMethodLast4: null,
    failedPaymentCount: 0,
  },
  {
    id: "sub-4",
    organization: "Nova Media Ltd",
    organizationId: "org-4",
    plan: "Growth",
    status: "Suspended",
    billingCycle: "Monthly",
    amount: 850,
    currency: "GBP",
    startDate: "2025-02-01",
    renewalDate: "2026-06-01",
    paymentMethodLast4: "1111",
    failedPaymentCount: 3,
  },
  {
    id: "sub-5",
    organization: "Zenith Agri",
    organizationId: "org-5",
    plan: "Starter",
    status: "Inactive",
    billingCycle: "Monthly",
    amount: 99,
    currency: "USD",
    startDate: "2025-08-20",
    renewalDate: null,
    paymentMethodLast4: null,
    failedPaymentCount: 0,
  },
  {
    id: "sub-6",
    organization: "Cyberdyne Systems",
    organizationId: "org-7",
    plan: "Enterprise",
    status: "Active",
    billingCycle: "Monthly",
    amount: 4500,
    currency: "USD",
    startDate: "2025-09-01",
    renewalDate: "2026-07-01",
    paymentMethodLast4: "8888",
    failedPaymentCount: 0,
  },
  {
    id: "sub-7",
    organization: "Wayne Enterprises",
    organizationId: "org-9",
    plan: "Enterprise",
    status: "Active",
    billingCycle: "Annual",
    amount: 480000,
    currency: "USD",
    startDate: "2023-10-01",
    renewalDate: "2026-10-01",
    paymentMethodLast4: "0007",
    failedPaymentCount: 0,
  },
  {
    id: "sub-8",
    organization: "Umbrella Biotech",
    organizationId: "org-10",
    plan: "Enterprise",
    status: "Suspended",
    billingCycle: "Monthly",
    amount: 3500,
    currency: "USD",
    startDate: "2025-03-15",
    renewalDate: "2026-06-15",
    paymentMethodLast4: null,
    failedPaymentCount: 1,
  },
];

const initialFeatureFlags: FeatureFlag[] = [
  {
    id: "flag-1",
    key: "ai_scheduling",
    name: "AI Assistant Co-Pilot",
    description:
      "Enables Gemini-powered smart task suggestions, auto-tagging, and intelligent support routing.",
    category: "Beta",
    status: "Active",
    defaultState: true,
    rolloutPct: 100,
    enabledPlans: ["Enterprise", "Growth"],
    enabledOrgIds: [],
    createdAt: "2026-01-10T12:00:00Z",
    updatedAt: "2026-06-15T09:30:00Z",
  },
  {
    id: "flag-2",
    key: "bulk_import_v2",
    name: "Excel/CSV Bulk Importer Core v2",
    description:
      "Allows background imports of up to 50,000 employees asynchronously with real-time error parsing.",
    category: "Core",
    status: "Active",
    defaultState: true,
    rolloutPct: 100,
    enabledPlans: ["Starter", "Growth", "Enterprise"],
    enabledOrgIds: [],
    createdAt: "2025-11-20T08:00:00Z",
    updatedAt: "2026-04-01T15:10:00Z",
  },
  {
    id: "flag-3",
    key: "mfa_enforce_all",
    name: "Mandatory Unified MFA",
    description:
      "Enforces multi-factor authentication locks on all organizational accounts on next log in.",
    category: "Core",
    status: "Active",
    defaultState: false,
    rolloutPct: 50,
    enabledPlans: ["Enterprise"],
    enabledOrgIds: ["org-1", "org-9"],
    createdAt: "2026-02-15T11:00:00Z",
    updatedAt: "2026-06-10T14:22:00Z",
  },
  {
    id: "flag-4",
    key: "advanced_geo_analytics",
    name: "Spatial Localization Engine",
    description:
      "Visual interactive maps to verify remote worker clock-ins with precision coordinates.",
    category: "Experimental",
    status: "Active",
    defaultState: false,
    rolloutPct: 10,
    enabledPlans: ["Enterprise"],
    enabledOrgIds: ["org-1"],
    createdAt: "2026-05-01T09:00:00Z",
    updatedAt: "2026-06-01T08:00:00Z",
  },
  {
    id: "flag-5",
    key: "custom_sso_portal",
    name: "Federated SAML 2.0 Branded Portals",
    description:
      "Allows organizations to wire white-labeled login domains (Okta, Azure AD, Shibboleth).",
    category: "Core",
    status: "Active",
    defaultState: true,
    rolloutPct: 100,
    enabledPlans: ["Enterprise"],
    enabledOrgIds: ["org-2"],
    createdAt: "2025-08-01T10:00:00Z",
    updatedAt: "2025-12-01T11:00:00Z",
  },
  {
    id: "flag-6",
    key: "slack_notifs_integration",
    name: "Slack Interactive Block Kit Alerts",
    description:
      "Broadcasts timesheet approvals and payroll alerts straight to client workspaces.",
    category: "Core",
    status: "Active",
    defaultState: true,
    rolloutPct: 100,
    enabledPlans: ["Growth", "Enterprise"],
    enabledOrgIds: [],
    createdAt: "2025-10-10T09:00:00Z",
    updatedAt: "2026-02-12T13:45:00Z",
  },
  {
    id: "flag-7",
    key: "legacy_time_clock_v1",
    name: "Legacy Flash-Based Clock Widget",
    description:
      "Deprecated timesheet input widget containing security warnings.",
    category: "Deprecated",
    status: "Inactive",
    defaultState: false,
    rolloutPct: 0,
    enabledPlans: [],
    enabledOrgIds: [],
    createdAt: "2022-04-01T00:00:00Z",
    updatedAt: "2026-01-01T00:00:00Z",
  },
];

const initialRoleTemplates: RoleTemplate[] = [
  {
    id: "role-1",
    name: "Platform Super Admin",
    description:
      "Has absolute root capability inside the dashboard structure. Restricted to platform operators.",
    scope: "Platform",
    status: "Active",
    permissions: [
      {
        module: "Organizations",
        actions: ["view", "create", "edit", "delete", "approve"],
      },
      { module: "Users", actions: ["view", "create", "edit", "delete"] },
      { module: "Billing", actions: ["view", "create", "edit", "delete"] },
      {
        module: "System Settings",
        actions: ["view", "create", "edit", "delete", "approve"],
      },
    ],
    assignedOrgCount: 1,
    isSystemDefault: true,
    updatedAt: "2026-01-01T00:00:00Z",
  },
  {
    id: "role-2",
    name: "Org Administrator",
    description:
      "Complete localized control of tenant properties, employees, invitations, branding and API logs.",
    scope: "Organization",
    status: "Active",
    permissions: [
      { module: "Employees", actions: ["view", "create", "edit", "delete"] },
      { module: "Payroll", actions: ["view", "create", "edit", "approve"] },
      { module: "Integrations", actions: ["view", "create", "edit"] },
      { module: "Branding", actions: ["view", "edit"] },
    ],
    assignedOrgCount: 10,
    isSystemDefault: true,
    updatedAt: "2026-01-01T00:00:00Z",
  },
  {
    id: "role-3",
    name: "Human Resource Manager",
    description:
      "Can view and edit employee dossiers, generate timesheet reports, run payroll approvals, but cannot modify API tokens.",
    scope: "Organization",
    status: "Active",
    permissions: [
      { module: "Employees", actions: ["view", "create", "edit"] },
      { module: "Payroll", actions: ["view", "create", "approve"] },
      { module: "Benefits", actions: ["view", "edit"] },
    ],
    assignedOrgCount: 45,
    isSystemDefault: true,
    updatedAt: "2026-01-01T00:00:00Z",
  },
  {
    id: "role-4",
    name: "Finance Auditor (Reviewer)",
    description:
      "Read-only access to invoice ledgers, payout sheets and payroll histories for audit runs.",
    scope: "Organization",
    status: "Active",
    permissions: [
      { module: "Payroll", actions: ["view"] },
      { module: "Billing", actions: ["view"] },
    ],
    assignedOrgCount: 12,
    isSystemDefault: false,
    updatedAt: "2026-04-18T10:30:00Z",
  },
  {
    id: "role-5",
    name: "Temporary Contractor Role",
    description:
      "Extremely restricted permissions configured for external contractors to log time sheets only.",
    scope: "Organization",
    status: "Inactive",
    permissions: [{ module: "Timesheets", actions: ["view", "create"] }],
    assignedOrgCount: 0,
    isSystemDefault: false,
    updatedAt: "2026-05-10T11:15:00Z",
  },
];

const initialIntegrations: Integration[] = [
  {
    id: "integ-1",
    name: "Okta Identity Provider",
    provider: "Okta",
    category: "SSO",
    status: "Active",
    connectedOrgCount: 4,
    authType: "SAML",
    lastSyncAt: "2026-06-20T01:10:00Z",
    healthStatus: "Healthy",
  },
  {
    id: "integ-2",
    name: "Microsoft Entra ID",
    provider: "Entra",
    category: "SSO",
    status: "Active",
    connectedOrgCount: 2,
    authType: "OAuth2",
    lastSyncAt: "2026-06-20T01:15:00Z",
    healthStatus: "Healthy",
  },
  {
    id: "integ-3",
    name: "Slack Communications Client",
    provider: "Slack",
    category: "Communication",
    status: "Active",
    connectedOrgCount: 8,
    authType: "OAuth2",
    lastSyncAt: "2026-06-20T00:50:00Z",
    healthStatus: "Healthy",
  },
  {
    id: "integ-4",
    name: "Google Calendar Workspace",
    provider: "Google Calendar",
    category: "Calendar",
    status: "Active",
    connectedOrgCount: 6,
    authType: "OAuth2",
    lastSyncAt: "2026-06-20T01:05:00Z",
    healthStatus: "Healthy",
  },
  {
    id: "integ-5",
    name: "ADP Workforce Payroll",
    provider: "ADP",
    category: "Payroll",
    status: "Pending",
    connectedOrgCount: 0,
    authType: "API Key",
    lastSyncAt: null,
    healthStatus: "Degraded",
  },
  {
    id: "integ-6",
    name: "Amazon S3 Active Storage",
    provider: "AWS S3",
    category: "Storage",
    status: "Active",
    connectedOrgCount: 10,
    authType: "API Key",
    lastSyncAt: "2026-06-19T22:30:00Z",
    healthStatus: "Healthy",
  },
  {
    id: "integ-7",
    name: "Mixpanel Analytics Stream",
    provider: "Mixpanel",
    category: "Analytics",
    status: "Inactive",
    connectedOrgCount: 3,
    authType: "API Key",
    lastSyncAt: null,
    healthStatus: "Down",
  },
];

const initialApiKeys: ApiKey[] = [
  {
    id: "key-1",
    label: "Production Timesheet API",
    organization: "Acme Enterprise",
    organizationId: "org-1",
    keyPrefix: "sk_live_v9Ax4L23",
    scopes: ["read:employees", "write:attendance", "read:payroll"],
    status: "Active",
    rateLimitPerMin: 1000,
    requestsToday: 23040,
    lastUsedAt: "2026-06-20T01:16:00Z",
    createdAt: "2024-02-01T08:00:00Z",
    expiresAt: null,
  },
  {
    id: "key-2",
    label: "ADP Sync Service",
    organization: "Apex Global",
    organizationId: "org-2",
    keyPrefix: "sk_live_p0Mv3N76",
    scopes: ["read:employees", "write:payroll"],
    status: "Active",
    rateLimitPerMin: 300,
    requestsToday: 4120,
    lastUsedAt: "2026-06-20T01:05:00Z",
    createdAt: "2024-06-10T09:00:00Z",
    expiresAt: "2026-12-31T23:59:59Z",
  },
  {
    id: "key-3",
    label: "Staging Test token",
    organization: "Cyberdyne Systems",
    organizationId: "org-7",
    keyPrefix: "sk_test_gT9b45eD",
    scopes: ["read:employees"],
    status: "Inactive",
    rateLimitPerMin: 100,
    requestsToday: 0,
    lastUsedAt: "2026-06-10T12:30:00Z",
    createdAt: "2025-09-02T11:00:00Z",
    expiresAt: "2026-06-01T00:00:00Z",
  },
  {
    id: "key-4",
    label: "Compliance Logger System",
    organization: "Wayne Enterprises",
    organizationId: "org-9",
    keyPrefix: "sk_live_b7Yw92eT",
    scopes: ["read:employees", "read:payroll", "write:employees"],
    status: "Active",
    rateLimitPerMin: 2000,
    requestsToday: 145020,
    lastUsedAt: "2026-06-20T01:17:00Z",
    createdAt: "2023-10-15T10:00:00Z",
    expiresAt: null,
  },
  {
    id: "key-5",
    label: "Malicious Query Key (Flagged)",
    organization: "Umbrella Biotech",
    organizationId: "org-10",
    keyPrefix: "sk_live_xX9v21zQ",
    scopes: [
      "read:employees",
      "write:employees",
      "read:payroll",
      "write:payroll",
    ],
    status: "Suspended",
    rateLimitPerMin: 50,
    requestsToday: 13,
    lastUsedAt: "2026-06-05T20:41:00Z",
    createdAt: "2025-03-20T12:00:00Z",
    expiresAt: null,
  },
];

const initialWebhookEndpoints: WebhookEndpoint[] = [
  {
    id: "web-1",
    organization: "Acme Enterprise",
    organizationId: "org-1",
    url: "https://api.acme.com/v1/callbacks/ems",
    events: ["user.created", "user.login", "subscription.renewed"],
    status: "Active",
    lastDeliveryStatus: "Success",
    lastDeliveredAt: "2026-06-20T01:00:00Z",
  },
  {
    id: "web-2",
    organization: "Wayne Enterprises",
    organizationId: "org-9",
    url: "https://secure-gateway.gotham.net/hooks",
    events: ["user.created", "user.deleted", "subscription.payment_failed"],
    status: "Active",
    lastDeliveryStatus: "Success",
    lastDeliveredAt: "2026-06-20T00:50:00Z",
  },
  {
    id: "web-3",
    organization: "Cyberdyne Systems",
    organizationId: "org-7",
    url: "https://skynet.net/receiver",
    events: ["user.login"],
    status: "Inactive",
    lastDeliveryStatus: "Failed",
    lastDeliveredAt: "2026-06-12T10:30:00Z",
  },
];

const initialAuditLogs: AuditLogEntry[] = [
  {
    id: "log-1",
    event: "user.login",
    eventCategory: "Auth",
    actor: "alice@acme.com",
    actorType: "org_admin",
    organization: "Acme Enterprise",
    ipAddress: "192.168.1.1",
    userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) Chrome/120.0.0",
    result: "Active",
    metadata: { mfa_method: "Authentic App", secure_enclave: "true" },
    timestamp: "2026-06-20T01:15:00Z",
  },
  {
    id: "log-2",
    event: "org.plan_upgrade",
    eventCategory: "Billing",
    actor: "billing@apex-corp.com",
    actorType: "org_admin",
    organization: "Apex Global",
    ipAddress: "84.120.44.21",
    userAgent: "Firefox/121.0 WebKit",
    result: "Active",
    metadata: {
      old_plan: "Starter",
      new_plan: "Growth",
      session_id: "sess_apex_9a91h2",
    },
    timestamp: "2026-06-20T00:45:00Z",
  },
  {
    id: "log-3",
    event: "security.mfa_bypass",
    eventCategory: "Security",
    actor: "albert.wesker@umbrellacorp.com",
    actorType: "org_admin",
    organization: "Umbrella Biotech",
    ipAddress: "140.231.90.8",
    userAgent: "Tor Browser/13.0.5",
    result: "Inactive",
    metadata: { fail_reason: "Signature mismatch on device payload" },
    timestamp: "2026-06-19T23:55:00Z",
  },
  {
    id: "log-4",
    event: "feature.toggle",
    eventCategory: "Admin Action",
    actor: "superadmin@emsplatform.com",
    actorType: "platform_admin",
    organization: null,
    ipAddress: "10.0.4.15",
    userAgent: "Chrome/120.0 AdminPanel",
    result: "Active",
    metadata: { feature_key: "ai_scheduling", status: "Active" },
    timestamp: "2026-06-19T18:30:00Z",
  },
  {
    id: "log-5",
    event: "user.invite_issued",
    eventCategory: "Admin Action",
    actor: "bruce@waynecorp.com",
    actorType: "org_admin",
    organization: "Wayne Enterprises",
    ipAddress: "100.22.44.11",
    userAgent: "Batcomputer OS v1.2",
    result: "Active",
    metadata: {
      invitee_email: "lucius@waynecorp.com",
      permissions: "HR Manager",
    },
    timestamp: "2026-06-19T16:20:00Z",
  },
  {
    id: "log-6",
    event: "backup.triggered",
    eventCategory: "Admin Action",
    actor: "System",
    actorType: "system",
    organization: null,
    ipAddress: "127.0.0.1",
    userAgent: "CronEngine/Service",
    result: "Active",
    metadata: {
      backup_id: "snap-daily-15893",
      path: "s3://ems-backups/prod/snap-15893.tar.gz",
    },
    timestamp: "2026-06-19T02:00:00Z",
  },
  {
    id: "log-7",
    event: "api.unauthorized_request",
    eventCategory: "Security",
    actor: "sk_live_xX9v21zQ",
    actorType: "system",
    organization: "Umbrella Biotech",
    ipAddress: "185.22.110.45",
    userAgent: "cUrl/7.84.0",
    result: "Inactive",
    metadata: {
      request_path: "/v1/payroll/export",
      reason: "Token Suspended for security breaches",
    },
    timestamp: "2026-06-18T14:10:00Z",
  },
];

const initialSupportTickets: SupportTicket[] = [
  {
    id: "tkt-1",
    subject: "SAML SSO Login failing with status 400",
    description:
      "Getting SAML Assertion validation failed on Acgo login endpoint. All active users cannot sign-in through Entra. Urgent help requested.",
    organization: "Acme Enterprise",
    organizationId: "org-1",
    submittedBy: "admin@acme.com",
    status: "Active",
    priority: "Critical",
    assignedTo: "Dave Miller",
    createdAt: "2026-06-20T00:30:00Z",
    updatedAt: "2026-06-20T01:10:00Z",
    firstResponseAt: "2026-06-20T00:45:00Z",
    resolvedAt: null,
    tags: ["SSO", "SAML", "Entra", "Urgent"],
  },
  {
    id: "tkt-2",
    subject: "Invoice mismatch in May annual subscription",
    description:
      "The annual billing invoice has an incorrect VAT number printed on it. We require a re-issued invoice to process this through accounts payable.",
    organization: "Apex Global",
    organizationId: "org-2",
    submittedBy: "billing@apex-corp.com",
    status: "Pending",
    priority: "Medium",
    assignedTo: "Emma Watson",
    createdAt: "2026-06-19T10:15:00Z",
    updatedAt: "2026-06-20T01:00:00Z",
    firstResponseAt: "2026-06-19T14:00:00Z",
    resolvedAt: null,
    tags: ["Billing", "VAT"],
  },
  {
    id: "tkt-3",
    subject: "How to configure custom webhook events?",
    description:
      "Is there support for subscription cancellation hooks in the web dashboard? We see user events but not subscriptions.",
    organization: "Cyberdyne Systems",
    organizationId: "org-7",
    submittedBy: "miles.dyson@cyberdyne.io",
    status: "Inactive",
    priority: "Low",
    assignedTo: "Alice Brown",
    createdAt: "2026-06-15T09:00:00Z",
    updatedAt: "2026-06-16T15:00:00Z",
    firstResponseAt: "2026-06-15T11:30:00Z",
    resolvedAt: "2026-06-16T15:00:00Z",
    tags: ["Webhooks", "API"],
  },
  {
    id: "tkt-4",
    subject: "Suspended warning showing on profile erroneously",
    description:
      "Our administration console dashboard displays a giant red banner claiming account suspended, but our cards were billed correctly yesterday. Please resolve ASAP.",
    organization: "Nova Media Ltd",
    organizationId: "org-4",
    submittedBy: "compliance@novamedia.co.uk",
    status: "Active",
    priority: "High",
    assignedTo: null,
    createdAt: "2026-06-20T01:00:00Z",
    updatedAt: "2026-06-20T01:00:00Z",
    firstResponseAt: null,
    resolvedAt: null,
    tags: ["Billing", "Suspension", "Erroneous"],
  },
];

const initialTicketMessages: TicketMessage[] = [
  {
    id: "msg-1",
    ticketId: "tkt-1",
    author: "admin@acme.com",
    authorType: "customer",
    body: "Hello, our Entra ID integration has started failing out of nowhere. No settings were altered. Getting Assertion Status XML validation error.",
    createdAt: "2026-06-20T00:30:00Z",
  },
  {
    id: "msg-2",
    ticketId: "tkt-1",
    author: "Dave Miller",
    authorType: "agent",
    body: "Hi Alice, I am looking into your assertion payload right now. We updated our signing certificates in Europe last night, which might require you to pull the metadata XML again. Let me check.",
    createdAt: "2026-06-20T00:45:00Z",
  },
  {
    id: "msg-3",
    ticketId: "tkt-1",
    author: "admin@acme.com",
    authorType: "customer",
    body: "Yes, downloading the latest certificate zip from Okta and matching it inside EMS cleared it for some users but still has issues for EMEA teams.",
    createdAt: "2026-06-20T01:10:00Z",
  },

  {
    id: "msg-4",
    ticketId: "tkt-2",
    author: "billing@apex-corp.com",
    authorType: "customer",
    body: "Please modify the registration ID for VAT. The company registry requires the prefix 'EU908234'.",
    createdAt: "2026-06-19T10:15:00Z",
  },
  {
    id: "msg-5",
    ticketId: "tkt-2",
    author: "Emma Watson",
    authorType: "agent",
    body: "Perfect. We are rebuilding the PDF snapshot manually. Let me ping back once compiled.",
    createdAt: "2026-06-19T14:00:00Z",
  },
];

const initialAnnouncements: Announcement[] = [
  {
    id: "ann-1",
    title: "Emergency Database Maintenance: UTC Sunday AM",
    body: "**Maintenance Notice**\n\nEMS platform database clusters will undergo critical security patching this Sunday, June 22nd, between 02:00 and 04:00 UTC. During this window, API keys and dashboards may see transient 502 errors for approximately 10 minutes.\n\nWe appreciate your patience.\n\n*Platform Operations Team*",
    audience: "All tenants",
    status: "Active",
    state: "Published",
    publishAt: "2026-06-20T00:00:00Z",
    expiresAt: "2026-06-23T04:00:00Z",
    displayStyle: "Banner",
    createdBy: "ops@emsplatform.com",
    viewCount: 1204,
    date: "2026-06-20",
  },
  {
    id: "ann-2",
    title: "New Feature Alert: Generative AI Support Agent v2",
    body: "# Gemini Co-Pilot is Ready!\n\nAll Growth and Enterprise organizations can now toggle the new **AI Autopilot** feature in the `AI Settings` tab. Once enabled, Gemini will automatically parse support inbound forms and provide automated drafts for HR Managers.\n\nRead the [documentation](https://docs.emsplatform.com/ai) to configure triggers.",
    audience: "Specific plan",
    audiencePlan: "Enterprise",
    status: "Active",
    state: "Published",
    publishAt: "2026-06-18T10:00:00Z",
    expiresAt: "2026-07-18T10:00:00Z",
    displayStyle: "Modal",
    createdBy: "marketing@emsplatform.com",
    viewCount: 450,
    date: "2026-06-18",
  },
  {
    id: "ann-3",
    title: "Scheduled Policy Revision - MFA Mandate",
    body: "Please review the updated platform terms of service. Mandatory MFA requirements for all organizational admins go into effect on July 1st, 2026.",
    audience: "All tenants",
    status: "Pending",
    state: "Scheduled",
    publishAt: "2026-06-25T08:00:00Z",
    expiresAt: "2026-07-25T08:00:00Z",
    displayStyle: "Notification Center Only",
    createdBy: "compliance@emsplatform.com",
    viewCount: 0,
    date: "2026-06-25",
  },
  {
    id: "ann-4",
    title: "Acme Custom Branding Welcome Note",
    body: "Corporate portal overrides successfully provisioned. Welcome to your custom dashboard.",
    audience: "Specific organizations",
    audienceOrgIds: ["org-1"],
    status: "Active",
    state: "Published",
    publishAt: "2026-01-15T08:00:00Z",
    expiresAt: null,
    displayStyle: "Notification Center Only",
    createdBy: "admin@acme.com",
    viewCount: 4500,
    date: "2026-01-15",
  },
];

const initialEmailTemplates: EmailTemplate[] = [
  {
    id: "tmpl-1",
    key: "user_invite",
    name: "User Invitation template",
    category: "Onboarding",
    subject: "You have been invited to join {{org_name}} on EMS Platform",
    bodyHtml:
      '<h2>Hello {{user_name}},</h2><p>You have been invited to join <strong>{{org_name}}</strong> as an active team member.</p><p><a href="{{invite_link}}" style="background:#6366F1;color:#fff;padding:8px 16px;text-decoration:none;border-radius:4px;">Accept Invitation</a></p><p>This link will expire in 7 days.</p>',
    status: "Active",
    variables: ["{{user_name}}", "{{org_name}}", "{{invite_link}}"],
    lastEditedBy: "superadmin@emsplatform.com",
    updatedAt: "2026-05-10T12:00:00Z",
    sentLast30Days: 4500,
  },
  {
    id: "tmpl-2",
    key: "password_reset",
    name: "Security Verification / Password Reset",
    category: "Security",
    subject: "Reset your EMS Platform password",
    bodyHtml:
      '<h2>Hello {{user_name}},</h2><p>We received a password reset request from your account. Click the button below to safe-configure a new lock:</p><p><a href="{{reset_link}}" style="background:#EF4444;color:#fff;padding:8px 16px;text-decoration:none;border-radius:4px;">Set New Password</a></p><p>If you did not request this, please forward this immediately to our compliance department.</p>',
    status: "Active",
    variables: ["{{user_name}}", "{{reset_link}}"],
    lastEditedBy: "compliance@emsplatform.com",
    updatedAt: "2025-12-01T15:00:00Z",
    sentLast30Days: 1204,
  },
  {
    id: "tmpl-3",
    key: "trial_ending_3days",
    name: "Trial Expiration Notice (3-Day Limit)",
    category: "Billing",
    subject: "Your free trial on EMS expires in 3 days!",
    bodyHtml:
      '<h2>Hello,</h2><p>Your team at <strong>{{org_name}}</strong> is nearing the end of your trial sandbox. To retain your structured personnel logs, please update your billing method today.</p><p><a href="{{billing_link}}" style="background:#10B981;color:#fff;padding:8px 16px;text-decoration:none;border-radius:4px;">Secure Plan Subscription</a></p>',
    status: "Active",
    variables: ["{{org_name}}", "{{billing_link}}"],
    lastEditedBy: "billing-bot@emsplatform.com",
    updatedAt: "2026-03-12T11:15:00Z",
    sentLast30Days: 85,
  },
  {
    id: "tmpl-4",
    key: "invoice_receipt",
    name: "Subscription Paid Receipt Invoice",
    category: "Billing",
    subject: "Invoice Paid successfully for date {{invoice_month}}",
    bodyHtml:
      "<h2>Payment Received</h2><p>Thank you for your active subscription on our platform. Your payment of {{amount}} has been credited. Invoice #{{invoice_number}} is compiled below.</p><p>Receipt code: <strong>{{receipt_hash}}</strong></p>",
    status: "Active",
    variables: [
      "{{invoice_month}}",
      "{{amount}}",
      "{{invoice_number}}",
      "{{receipt_hash}}",
    ],
    lastEditedBy: "billing-bot@emsplatform.com",
    updatedAt: "2026-06-01T08:00:00Z",
    sentLast30Days: 1450,
  },
];

const initialNotificationRules: NotificationRule[] = [
  {
    id: "rule-1",
    name: "Failed Subscription Payments",
    triggerEvent: "subscription.payment_failed",
    category: "Billing",
    channels: ["Email", "Slack"],
    recipientType: "Org Admins",
    status: "Active",
    throttle: "Immediate",
    updatedAt: "2026-01-10T12:00:00Z",
  },
  {
    id: "rule-2",
    name: "Ticket Escalation Lock",
    triggerEvent: "ticket.escalated",
    category: "Support",
    channels: ["Email", "Slack", "In-App"],
    recipientType: "Platform Admins",
    status: "Active",
    throttle: "Immediate",
    updatedAt: "2026-03-15T09:00:00Z",
  },
  {
    id: "rule-3",
    name: "Suspicious Location Login travel warnings",
    triggerEvent: "security.travel_mismatch",
    category: "Security",
    channels: ["Email", "In-App", "SMS"],
    recipientType: "Affected User",
    status: "Active",
    throttle: "Immediate",
    updatedAt: "2026-05-20T14:30:00Z",
  },
  {
    id: "rule-4",
    name: "Weekly General Performance Digest",
    triggerEvent: "reports.weekly_digest",
    category: "System",
    channels: ["Email"],
    recipientType: "Org Admins",
    status: "Active",
    throttle: "Digest - Hourly",
    updatedAt: "2026-02-01T10:00:00Z",
  },
];

const initialBackupSnapshots: BackupSnapshot[] = [
  {
    id: "snap-1",
    type: "Automatic",
    status: "Active",
    sizeGb: 28.4,
    createdAt: "2026-06-20T02:00:00Z",
    retentionExpiresAt: "2026-07-20T02:00:00Z",
    triggeredBy: "System (scheduled)",
  },
  {
    id: "snap-2",
    type: "Automatic",
    status: "Active",
    sizeGb: 28.3,
    createdAt: "2026-06-19T02:00:00Z",
    retentionExpiresAt: "2026-07-19T02:00:00Z",
    triggeredBy: "System (scheduled)",
  },
  {
    id: "snap-3",
    type: "Manual",
    status: "Active",
    sizeGb: 28.1,
    createdAt: "2026-06-18T14:15:00Z",
    retentionExpiresAt: "2026-07-18T14:15:00Z",
    triggeredBy: "Alice admin (ops)",
  },
  {
    id: "snap-4",
    type: "Automatic",
    status: "Inactive",
    sizeGb: 0,
    createdAt: "2026-06-17T02:00:00Z",
    retentionExpiresAt: "2026-06-17T02:05:00Z",
    triggeredBy: "System (failed: out of disk catalog segment)",
  },
];

const initialBackupSchedule: BackupSchedule = {
  frequency: "Daily",
  retentionDays: 30,
  time: "02:00",
  enabled: true,
};

const initialBrandingConfigs: BrandingConfig[] = [
  {
    scope: "Platform Default",
    logoUrl: "",
    faviconUrl: "",
    primaryColor: "#6366F1",
    accentColor: "#F43F5E",
    customDomain: "admin.emsplatform.com",
    domainVerified: true,
    emailFromName: "EMS Ops Desk",
    updatedAt: "2026-01-01T08:00:00Z",
  },
  {
    scope: "Organization Override",
    organizationId: "org-1",
    logoUrl: "",
    faviconUrl: "",
    primaryColor: "#0F172A",
    accentColor: "#10B981",
    customDomain: "portal.acme.com",
    domainVerified: true,
    emailFromName: "Acme Talent Hub",
    updatedAt: "2026-01-16T10:30:00Z",
  },
  {
    scope: "Organization Override",
    organizationId: "org-2",
    logoUrl: "",
    faviconUrl: "",
    primaryColor: "#3B82F6",
    accentColor: "#F59E0B",
    customDomain: "hr.apex-corp.com",
    domainVerified: false,
    emailFromName: "Apex HR Office",
    updatedAt: "2026-05-12T14:00:00Z",
  },
];

const initialSecurityPolicy: SecurityPolicy = {
  passwordMinLength: 12,
  passwordRequireSymbol: true,
  passwordRequireNumber: true,
  passwordExpiryDays: 90,
  mfaEnforcement: "Required for Admins",
  sessionTimeoutMinutes: 30,
  maxConcurrentSessions: 3,
  ipAllowlist: [
    {
      id: "ip-1",
      label: "HQ London Office Router",
      cidr: "82.140.231.0/24",
      addedAt: "2024-01-20T10:00:00Z",
    },
    {
      id: "ip-2",
      label: "Cloud Run Outbound Proxy IP",
      cidr: "198.51.100.45/32",
      addedAt: "2026-01-10T11:00:00Z",
    },
  ],
  ssoEnforced: false,
};

const initialSecurityEvents: SecurityEvent[] = [
  {
    id: "sec-evt-1",
    type: "Failed Login Spike",
    organization: "Umbrella Biotech",
    actor: "albert.wesker@umbrellacorp.com",
    severity: "Critical",
    status: "Active",
    detectedAt: "2026-06-20T01:05:00Z",
  },
  {
    id: "sec-evt-2",
    type: "Impossible Travel",
    organization: "Acme Enterprise",
    actor: "bob@acme.com",
    severity: "High",
    status: "Pending",
    detectedAt: "2026-06-19T22:30:00Z",
  },
  {
    id: "sec-evt-3",
    type: "MFA Disabled",
    organization: "Stellar Tech SRL",
    actor: "contact@stellar.io",
    severity: "Medium",
    status: "Inactive",
    detectedAt: "2026-06-18T15:20:00Z",
  },
];

const initialAiFeatureToggles: AiFeatureToggle[] = [
  {
    id: "ai-f-1",
    key: "churn_risk_radar",
    name: "Churn Risk Radar AI Detector",
    description:
      "Evaluates support tickets volume, API failure counts, and system inactivity logs to calculate client cancellation risk values.",
    status: "Active",
    enabledPlans: ["Enterprise", "Growth"],
    confidenceThreshold: 75,
    dataRetentionDays: 90,
  },
  {
    id: "ai-f-2",
    key: "support_copilot",
    name: "Helpdesk Support Smart Autoprep",
    description:
      "Scans active ticket messages, indexes company documentation resources, and drafts contextual replies directly inside the Support console.",
    status: "Active",
    enabledPlans: ["Enterprise"],
    confidenceThreshold: 85,
    dataRetentionDays: 60,
  },
  {
    id: "ai-f-3",
    key: "anomaly_watch",
    name: "Timesheet / Attendance Suspicion Scanner",
    description:
      "Watches geometric remote lockouts and anomalous shift timings to warn compliance officers automatically.",
    status: "Inactive",
    enabledPlans: ["Enterprise"],
    confidenceThreshold: 90,
    dataRetentionDays: 120,
  },
];

const initialAiUsageStats: AiUsageStat[] = [
  {
    feature: "Churn Risk Radar AI Detector",
    callsLast30Days: 12050,
    avgLatencyMs: 380,
    estimatedCost: 1.25,
  },
  {
    feature: "Helpdesk Support Smart Autoprep",
    callsLast30Days: 34500,
    avgLatencyMs: 820,
    estimatedCost: 17.25,
  },
  {
    feature: "Timesheet / Attendance Suspicion Scanner",
    callsLast30Days: 0,
    avgLatencyMs: 0,
    estimatedCost: 0,
  },
];

const initialPlatformSettings: PlatformSettings = {
  platformName: "EMS Enterprise Platform Admin Console",
  supportEmail: "compliance@emsplatform.com",
  defaultTimezone: "UTC",
  defaultLocale: "en-US",
  defaultCurrency: "USD",
  maintenanceMode: false,
};

const initialAdminTeamMembers: AdminTeamMember[] = [
  {
    id: "adm-1",
    name: "Pradeep Kumar (You)",
    email: "admin@ems.io",
    role: "Super Admin",
    status: "Active",
    lastLoginAt: "2026-06-20T01:17:59-07:00",
    invitedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "adm-2",
    name: "David Miller",
    email: "dave.miller@emsplatform.com",
    role: "Support Lead",
    status: "Active",
    lastLoginAt: "2026-06-20T00:45:00Z",
    invitedAt: "2024-01-10T10:00:00Z",
  },
  {
    id: "adm-3",
    name: "Emma Watson",
    email: "emma.watson@emsplatform.com",
    role: "Billing Admin",
    status: "Active",
    lastLoginAt: "2026-06-19T14:00:00Z",
    invitedAt: "2024-03-01T09:00:00Z",
  },
  {
    id: "adm-4",
    name: "Auditor John",
    email: "john.audit@emsplatform.com",
    role: "Read Only",
    status: "Pending",
    lastLoginAt: null,
    invitedAt: "2026-06-15T11:00:00Z",
  },
];

// ==========================================
// STATE MANAGEMENT CONTEXT
// ==========================================

export const db = {
  organizations: {
    get: () => getStore<Organization[]>("organizations", initialOrganizations),
    save: (data: Organization[]) => saveStore("organizations", data),
  },
  users: {
    get: () => getStore<PlatformUser[]>("users", initialUsers),
    save: (data: PlatformUser[]) => saveStore("users", data),
  },
  subscriptions: {
    get: () => getStore<Subscription[]>("subscriptions", initialSubscriptions),
    save: (data: Subscription[]) => saveStore("subscriptions", data),
  },
  featureFlags: {
    get: () => getStore<FeatureFlag[]>("featureFlags", initialFeatureFlags),
    save: (data: FeatureFlag[]) => saveStore("featureFlags", data),
  },
  roleTemplates: {
    get: () => getStore<RoleTemplate[]>("roleTemplates", initialRoleTemplates),
    save: (data: RoleTemplate[]) => saveStore("roleTemplates", data),
  },
  integrations: {
    get: () => getStore<Integration[]>("integrations", initialIntegrations),
    save: (data: Integration[]) => saveStore("integrations", data),
  },
  apiKeys: {
    get: () => getStore<ApiKey[]>("apiKeys", initialApiKeys),
    save: (data: ApiKey[]) => saveStore("apiKeys", data),
  },
  webhooks: {
    get: () => getStore<WebhookEndpoint[]>("webhooks", initialWebhookEndpoints),
    save: (data: WebhookEndpoint[]) => saveStore("webhooks", data),
  },
  auditLogs: {
    get: () => getStore<AuditLogEntry[]>("auditLogs", initialAuditLogs),
    save: (data: AuditLogEntry[]) => saveStore("auditLogs", data),
  },
  tickets: {
    get: () => getStore<SupportTicket[]>("tickets", initialSupportTickets),
    save: (data: SupportTicket[]) => saveStore("tickets", data),
  },
  ticketMessages: {
    get: () =>
      getStore<TicketMessage[]>("ticketMessages", initialTicketMessages),
    save: (data: TicketMessage[]) => saveStore("ticketMessages", data),
  },
  announcements: {
    get: () => getStore<Announcement[]>("announcements", initialAnnouncements),
    save: (data: Announcement[]) => saveStore("announcements", data),
  },
  emailTemplates: {
    get: () =>
      getStore<EmailTemplate[]>("emailTemplates", initialEmailTemplates),
    save: (data: EmailTemplate[]) => saveStore("emailTemplates", data),
  },
  notificationRules: {
    get: () =>
      getStore<NotificationRule[]>(
        "notificationRules",
        initialNotificationRules,
      ),
    save: (data: NotificationRule[]) => saveStore("notificationRules", data),
  },
  backups: {
    get: () => getStore<BackupSnapshot[]>("backups", initialBackupSnapshots),
    save: (data: BackupSnapshot[]) => saveStore("backups", data),
    getSchedule: () =>
      getStore<BackupSchedule>("backups_schedule", initialBackupSchedule),
    saveSchedule: (data: BackupSchedule) => saveStore("backups_schedule", data),
  },
  branding: {
    get: () => getStore<BrandingConfig[]>("branding", initialBrandingConfigs),
    save: (data: BrandingConfig[]) => saveStore("branding", data),
  },
  security: {
    getPolicy: () =>
      getStore<SecurityPolicy>("security_policy", initialSecurityPolicy),
    savePolicy: (data: SecurityPolicy) => saveStore("security_policy", data),
    getEvents: () =>
      getStore<SecurityEvent[]>("security_events", initialSecurityEvents),
    saveEvents: (data: SecurityEvent[]) => saveStore("security_events", data),
  },
  ai: {
    getToggles: () =>
      getStore<AiFeatureToggle[]>("ai_toggles", initialAiFeatureToggles),
    saveToggles: (data: AiFeatureToggle[]) => saveStore("ai_toggles", data),
    getStats: () => getStore<AiUsageStat[]>("ai_stats", initialAiUsageStats),
    saveStats: (data: AiUsageStat[]) => saveStore("ai_stats", data),
  },
  settings: {
    getPlatform: () =>
      getStore<PlatformSettings>("platform_settings", initialPlatformSettings),
    savePlatform: (data: PlatformSettings) =>
      saveStore("platform_settings", data),
    getTeam: () =>
      getStore<AdminTeamMember[]>("admin_team", initialAdminTeamMembers),
    saveTeam: (data: AdminTeamMember[]) => saveStore("admin_team", data),
  },
};

// Helper: Push a new Audit Log entry
export function pushAuditLog(
  event: string,
  category: AuditLogEntry["eventCategory"],
  actor: string,
  actorType: AuditLogEntry["actorType"],
  organization: string | null,
  result: "Active" | "Inactive",
  metadata: Record<string, string>,
) {
  const current = db.auditLogs.get();
  const newLog: AuditLogEntry = {
    id: `log-${Date.now()}`,
    event,
    eventCategory: category,
    actor,
    actorType,
    organization,
    ipAddress: "198.51.100.12",
    userAgent: "Google Chrome/124.0.0 (Admin Session)",
    result,
    metadata,
    timestamp: new Date().toISOString(),
  };
  db.auditLogs.save([newLog, ...current]);
}
